---
ansible_python_interpreter: "{{ ansible_playbook_python }}"

registry_username: ""
registry_password: ""

image_registry: "ghcr.io"
image_name: "bluehorndigital/mojo"
image_tag: ""

database_host: ""
database_port: ""
database_name: ""
database_user: ""
database_password: ""

hostname: ""

hash_salt: ""

object_storage_access_key: ""
object_storage_secret_key: ""
