name: PHPUnit
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        php: [7.4, 8.0]
        os: [ubuntu-latest]
    name: tests - ${{ matrix.php }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.composer/cache/files
            ~/.composer/cache/repo
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pdo, mysql, pdo_mysql, bcmath, soap, intl, gd, exif, iconv
          coverage: none
          tools: composer:v2
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: PHPUnit
        run: php vendor/bin/phpunit web/modules/mojo
